### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aloisdg**

### CODE REVIEW

**Comment by danhuss** [comment]
Updated this to take the previous pull request into account. It's merged into master now.

**Comment by aloisdg** [comment]
You can make a proper merge directly.

**Comment by danhuss** [comment]
Not directly on github. The changes were on the same lines so it's like it was conflicted after merging request 1. I pulled it down on my machine to resolve and merge them. History looks right and you're credited with the change so I wasn't worried about it.

disclaimer: I'm by no means a git expert so there could very well have been a better way to do that that I didn't know about.

**Comment by aloisdg** [comment]
Ok no problem. :)

**Pull request closed without merging**
